CREATE TABLE IF NOT EXISTS customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_products_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_products_stock_non_negative CHECK (stock >= 0)
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(40) NOT NULL UNIQUE,
    customer_id INTEGER NOT NULL REFERENCES customers(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_orders_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_orders_price_non_negative CHECK (unit_price >= 0)
);

INSERT INTO customers (name, email)
VALUES
    ('Ana Souza', 'ana.souza@example.com'),
    ('Bruno Lima', 'bruno.lima@example.com'),
    ('Carla Mendes', 'carla.mendes@example.com')
ON CONFLICT (email) DO NOTHING;

INSERT INTO products (sku, name, description, price, stock)
VALUES
    (
        'NOTEBOOK-001',
        'Notebook Pro 14',
        'Notebook de 14 polegadas com 16 GB de memória.',
        5499.90,
        8
    ),
    (
        'MOUSE-001',
        'Mouse sem fio',
        'Mouse ergonômico com conexão Bluetooth.',
        149.90,
        35
    ),
    (
        'MONITOR-001',
        'Monitor 27 polegadas',
        'Monitor IPS com resolução QHD.',
        1899.00,
        12
    )
ON CONFLICT (sku) DO NOTHING;

INSERT INTO orders (
    order_number,
    customer_id,
    product_id,
    quantity,
    unit_price,
    status
)
SELECT
    seed.order_number,
    customers.id,
    products.id,
    seed.quantity,
    products.price,
    seed.status
FROM (
    VALUES
        ('PEDIDO-1001', 'ana.souza@example.com', 'NOTEBOOK-001', 1, 'paid'),
        ('PEDIDO-1002', 'bruno.lima@example.com', 'MOUSE-001', 2, 'shipped'),
        ('PEDIDO-1003', 'carla.mendes@example.com', 'MONITOR-001', 1, 'pending')
) AS seed(order_number, customer_email, product_sku, quantity, status)
JOIN customers ON customers.email = seed.customer_email
JOIN products ON products.sku = seed.product_sku
ON CONFLICT (order_number) DO NOTHING;
